# Generated by Django 4.0.2 on 2022-03-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendances',
            options={'managed': False, 'verbose_name': 'attendance', 'verbose_name_plural': 'attendances'},
        ),
        migrations.AlterModelOptions(
            name='attendancesummaries',
            options={'managed': False, 'verbose_name': 'attendance_summary', 'verbose_name_plural': 'attendance_summaries'},
        ),
        migrations.AlterModelOptions(
            name='chapels',
            options={'managed': False, 'verbose_name': 'chapel', 'verbose_name_plural': 'chapels'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'managed': False, 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'managed': False, 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
    ]
