# Generated by Django 3.2.5 on 2022-05-06 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchDashboard', '0002_alter_attendances_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shepherd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=6, null=True)),
                ('chapel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chapel_shepherds', to='ChurchDashboard.chapels')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_shepherds', to='ChurchDashboard.groups')),
            ],
        ),
    ]
