# Generated by Django 4.0.2 on 2022-03-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccounts',
            options={'verbose_name': 'useraccount', 'verbose_name_plural': 'useraccounts'},
        ),
    ]
