# Generated by Django 4.0.2 on 2022-04-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccounts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='username',
        ),
    ]
